export const streamers = {
  streamerArray1: [
    "html",
    "javascript",
    "css",
    "typescript",
    "reactjs",
    "nextjs",
    "tailwind",
    "nodejs",
    "firebase",
    "illustrator",
    "after effects",
  ],
  streamerArray2: [
    "motion graphics",
    "ui/ux",
    "full-stack",
    "frontend",
    "hci",
    "web design",
    "software development",
    "product design",
  ],
};
